# Generated by Django 4.0.3 on 2023-04-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hats_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationvo',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
