# Generated by Django 4.0.3 on 2023-04-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hats_rest', '0002_alter_locationvo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hat',
            name='picture_url',
            field=models.URLField(default=''),
        ),
    ]
