# Generated by Django 4.0.3 on 2023-04-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hats_rest", "0003_hat_picture_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="locationvo",
            name="import_href",
        ),
        migrations.RemoveField(
            model_name="locationvo",
            name="name",
        ),
        migrations.AddField(
            model_name="locationvo",
            name="closet_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="locationvo",
            name="section_number",
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="locationvo",
            name="shelf_number",
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
    ]
