# Generated by Django 4.0.3 on 2023-04-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='picture_url',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
